### ISSUE TITLE
If the current script running is a symbolic link fix application path with the real path

### ISSUE THREAD

**Issue by piraz** [candango/myfuses#97]
If the user decides to link the index.php or the front controller page on a different path we should resolve the link path and set the real path into the application.

For instance, the application path is located at /home/user/app and index.php is the front controller or index script.

The user is having problems on nginx because circuits are under the application path and the default circuit actions cannot be resolved because nginx is finding a directory with the circuit name and returning a 403 instead of redirecting the request to the front controller.

Instead of changing my application directories or getting my nginx config really complicated I decide to create another directory /opt/www/app and create a symbolic link pointing to /home/user/app/index.php there.

Right now myfuses will set the app path as /opt/www/app instead of /home/user/app and we won't be able to read the app and circuits xml files.

Let's follow the link and set the application path as /opt/www/app.

**Comment by michael-lins** [comment]
oh ok, by link you mean symbolic link! Now I get it.
